### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by AaroncrowAries** [tttianhao/CLEAN#9]
The online website does not work, and error reported in the local training. Which always reported that there is No such file or directory: './data/esm_data/P76077_4.pt'.

Traceback (most recent call last):
  File "/home/yangshihui/CLEAN/./train-triplet.py", line 138, in <module>
    main()
  File "/home/yangshihui/CLEAN/./train-triplet.py", line 117, in main
    train_loss = train(model, args, epoch, train_loader,
  File "/home/yangshihui/CLEAN/./train-triplet.py", line 44, in train
    for batch, data in enumerate(train_loader):
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/CLEAN-0.1-py3.10.egg/CLEAN/dataloader.py", line 76, in __getitem__
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/esm_data/P76077_4.pt'
Traceback (most recent call last):
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/CLEAN-0.1-py3.10.egg/CLEAN/infer.py", line 90, in infer_maxsep
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yangshihui/miniconda3/envs/clean/lib/python3.10/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained/split100.pth'

**Comment by tttianhao** [comment]
No such file or directory: './data/esm_data/P76077_4.pt'. indicates ESM embeddings are not generated as expected. And FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained/split100.pth' means you did not download the pre-trained weights. If your goal is to inference, you may follow the quick guide in readme section 1.2 step-by-step. Please let me know if that step-by-step guide does not work for you. The website is current under maintenance and will be available again in a few days.

**Comment by AaroncrowAries** [comment]
> No such file or directory: './data/esm_data/P76077_4.pt'. indicates ESM embeddings are not generated as expected. And FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained/split100.pth' means you did not download the pre-trained weights. If your goal is to inference, you may follow the quick guide in readme section 1.2 step-by-step. Please let me know if that step-by-step guide does not work for you. The website is current under maintenance and will be available again in a few days.

Thanks a lot, It's work
